on: push
name: 🚀 Deploy to FTP on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.devolution.online
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
